repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-json
        exclude: ^\.envrc$
      - id: check-symlinks
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: a27a2e47c7751b639d2b5badf0ef6ff11fee893f # frozen: v0.15.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 92110f8f7c622b1f544fd9b509fd3588e4bec7c2 # frozen: v0.10.6
    hooks:
      - id: uv-lock
