name: TY Check

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  # TODO: Move to pre-commit once the official hook is released: https://github.com/astral-sh/ty/issues/269
  ty-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --dev

      - name: Type check src
        run: uv run ty check src
